// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnrWs06_LS4ECnZzPVyLSMPLvWTs1CRlk',
    appId: '1:447218684599:web:426049b8b12b4e49813332',
    messagingSenderId: '447218684599',
    projectId: 'frutiexpress-73ce9',
    authDomain: 'frutiexpress-73ce9.firebaseapp.com',
    storageBucket: 'frutiexpress-73ce9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevOjyMsNQ1IO2a3b3nYjko4xj4B07C8w',
    appId: '1:447218684599:android:0e348f431daff493813332',
    messagingSenderId: '447218684599',
    projectId: 'frutiexpress-73ce9',
    storageBucket: 'frutiexpress-73ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrVNvmJi7DtnRqIUqSqawpHUrPAYQTgY',
    appId: '1:447218684599:ios:b22b18074916a30c813332',
    messagingSenderId: '447218684599',
    projectId: 'frutiexpress-73ce9',
    storageBucket: 'frutiexpress-73ce9.firebasestorage.app',
    iosBundleId: 'com.example.frutiExpressJahr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrVNvmJi7DtnRqIUqSqawpHUrPAYQTgY',
    appId: '1:447218684599:ios:b22b18074916a30c813332',
    messagingSenderId: '447218684599',
    projectId: 'frutiexpress-73ce9',
    storageBucket: 'frutiexpress-73ce9.firebasestorage.app',
    iosBundleId: 'com.example.frutiExpressJahr',
  );
}
